#!/bin/sh

# Helper function for error reporting.
die() { [ $# -gt 0 ] && echo "$*" >&2; exit 1; }

requiredUtils='bash say osascript'    # Add additional prerequisites, if any, here.
for requiredUtil in $requiredUtils; do
  [ -n "$(command -v "$requiredUtil")" ] || die "MISSING PREREQUISITE: \`$requiredUtil\` is required to run tests."
done
