#!/usr/bin/env bash

# ---
# IMPORTANT: Use the following statement at the TOP OF EVERY TEST SCRIPT
#            to ensure that this package's 'bin/' subfolder is added to the path so that
#            this package's CLIs can be invoked by their mere filename in the rest
#            of the script.
# ---
PATH=${PWD%%/test*}/bin:$PATH

# Helper function for error reporting.
die() { (( $# > 0 )) && echo "ERROR: $*" >&2; exit 1; }

defaultVoice=$(defaults read com.apple.speech.voice.prefs SelectedVoiceName)

shopt -s nocasematch
[[ $(voices -b) == "$defaultVoice" ]] || die "Default voice reported did not match '$defaultVoice'."

exit 0
